### ISSUE TITLE
Record Type allows non-defined keys

### ISSUE THREAD

**Issue by richardboehme** [soutaro/steep#1046]
When defining a record type, I expected the type checker to complain if an additional (non-defined) key was supplied by the user. Specifically I expected the following to fail type checking:

```ruby
# @type var x: { name: String }
x = { name: "foo", bar: 'foo' }
```

Is my assumption wrong or is this a bug in Steep? Might it be related with the change in #256?

Version tested: 1.6.0

**Comment by soutaro** [comment]
It makes sense. Reporting unknown keys included in literals should help.

**Comment by ParadoxV5** [comment]
*Comment moved from #256*

> * Allows skipping `nil`-able attributes
> 
> ```
> # @type var x: { name: String, email: String? }
> x = { name: "foo" }                                    # OK 🐕 
> ```

Ackchyually nonexistent key is distinguishable from `nil` values for non-implicit-nil methods such as `x.fetch :email`.

```ruby
# @type var x: { name: String, ?email: String? }
x = { name: "foo" }  # OK 💯
```
