### ISSUE TITLE
UnknownTypeName exception on 3rd party type signature

### ISSUE THREAD

**Issue by carltablante1** [soutaro/steep#1103]
## Summary

`steep check` raises an error and references a Gem's RBS file. The issue seems to be that steep couldn't tell that the type definitions that the gem was using is from the Ruby standard library e.g. `OptionParser`, `Pathname.`

Check the `notes` section for my workaround.

## Steps to replicate

You can use my test repo to recreate it. [https://github.com/carlqt/toyrobo-ruby](https://github.com/carlqt/toyrobo-ruby)

*   Clone the repo
*   Navigate to `anyway-config-error` branch
*   Run `bundle install` and `rbs collection install`
*   Run `steep check`

## Screenshots

![](https://github.com/soutaro/steep/assets/148743026/1585e056-8ce6-4568-b244-99f15e338294)

## NOTES:

I can fix it by adding `optparse` and `pathname` to my own `rbs_collection.yaml`

**Comment by ParadoxV5** [comment]
It’s good practice to add stdlib gems to your `.gemspec`. My rule of thumb is simple: If I need to `require` it, I add it to `Gemfile`/`.gemspec`.

**Comment by carltablante1** [comment]
That makes sense but, if it wasn't clear, I'm not using `optparse` and `pathname` . The 3rd party gem was using them and I'm getting this error

**Comment by soutaro** [comment]
I was assuming [manifest.yaml](https://github.com/palkan/anyway_config/blob/master/sig/manifest.yml) is for this, but the file has `optparse` and `pathname`. Let me try myself on your code.

**Comment by soutaro** [comment]
The `anyway_config` ships with `manifest.yml`, but rbs-gem requires `manifest.yaml`...

So, the workaround is having the libraries in `rbs_collection.yaml`, as you noted. (And I will open a PR on anyway_config, which renames the file to `manifest.yaml`.)

**Comment by carltablante1** [comment]
Thanks everyone. Glad to learn something new today. :smiley\_cat:
