### ISSUE TITLE
LSP "response id must be a number" error in neovim

### ISSUE THREAD

**Issue by nickjer** [soutaro/steep#1246]
Just want to first say this is an amazing project. I have been using the LSP server in the 1.7.1 release for awhile now with no issues in neovim.

But I just recently upgraded `steep` to 1.8.0 and now neovim is providing a stacktrace:

```
Error executing luv callback:                                                                                                                                                                             
...nt_nvimwcukvL/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:462: response id must be a number                                                                                                             
stack traceback:                                                                                                                                                                                          
        [C]: in function 'assert'                                                                                                                                                                         
        ...nt_nvimwcukvL/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:462: in function 'handle_body'                                                                                                        
        ...nt_nvimwcukvL/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:765: in function 'handle_body'                                                                                                        
        ...nt_nvimwcukvL/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:267: in function <...nt_nvimwcukvL/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:251>
```

I wasn't entirely sure if I should be posting this issue here, but the only thing that changed was going from `steep` 1.7.1 to 1.8.0. If I downgrade back to 1.7.1 then it goes away.

Feel free to close this issue if you feel it has nothing to do with `steep`. I lack the expertise here to say one way or the other.

**Comment by nickjer** [comment]
Alright, I have since updated my neovim to the latest nightly release `NVIM v0.11.0-dev-881+g865ba42e0` and I do not see this issue anymore. I'll close this issue since I cannot reproduce it anymore.

**Comment by soutaro** [comment]
@nickjer Thank you for letting us know this issue.

If it's about the LSP messages, it might be an issue of neovim because the spec says they can be a string. https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#requestMessage

It's possible to make them numbers in Steep technically, but I want to know more detail of the problem.

1. Is it about LSP messages?
2. How is the opinion of neovim team?

**Comment by nickjer** [comment]
I did finally manage to dump logs from neovim. Even in `steep` 1.7.1 I do see String id's (on occasion) and that ran just fine, so I am not sure what is causing the crash with 1.8.0.

I did note the comment above the problem line:

https://github.com/neovim/neovim/blob/c6abc97006eee7fc89baefad2e1bddb248187f2e/runtime/lua/vim/lsp/rpc.lua#L461-L462

```
-- We sent a number, so we expect a number.
```

Was there any change to `steep` 1.8.0 that would cause the id to be different than what was sent to it?

In the meantime I'll also open up an issue on the neovim repo. Thanks for following up.

**Comment by soutaro** [comment]
Thank you very much for the investigation!

Yeah, it looks like [the response](https://github.com/neovim/neovim/issues/30638#issuecomment-2391279766) is something Steep is using for internal communication. I don't know how can the message be sent to the client, but it's clear I need to fix a bug. 🙇‍♂️

**Comment by soutaro** [comment]
@nickjer Hi! I hope #1267 fixes the problem and released 1.8.1 with the backport. So, can you try the version when you have time?

**Comment by nickjer** [comment]
It works! Thanks so much @soutaro :tada:

**Comment by nickjer** [comment]
Curious if this has regressed? I am seeing the error again. I might need to bisect when this started.
