### ISSUE TITLE
Steep does not support %a{implicitly-returns-nil} annotation

### ISSUE THREAD

**Issue by tk0miya** [soutaro/steep#1251]
Since RBS-3.6, some core methods have been annotated as `%a{implicitly-returns-nil}` and do not return nil in type definitions (see https://github.com/ruby/rbs/pull/1921).

However Steep does not support the annotation. So it emits unexpected warnings to users.

For example, Steep emits `UnreachableBranch` for the following code:

```
item = [1, 2, 3].first

if item
  puts "Item is #{item}"
else
  puts "Item is nil"
end
```

Result:
```
$ bundle exec steep check --severity=information
# Type checking files:

.........................................................................................................................................................................................................................................................................................F.

app/app.rb:5:0: [information] The branch is unreachable
│ Diagnostic ID: Ruby::UnreachableBranch
│
└ else
  ~~~~

Detected 1 problem from 1 file
```

Steepfile:

```
D = Steep::Diagnostic

target :app do
  signature "sig"
  check "app"

  configure_code_diagnostics(D::Ruby.strict)
end
```

Environment:

* Steep 1.7.1 or 1.8.0
* RBS 3.6.1

The warning is not emitted with RBS-3.5.3.

```
$ bundle exec steep check --severity=information
# Type checking files:

..........................................................................................................................................................................................................................................................................................

No type error detected. 🫖
```

**Comment by nickjer** [comment]
Looks like this is related to the PR: https://github.com/soutaro/steep/pull/1258

**Comment by soutaro** [comment]
Yes. I think this is done with #1258.

**Comment by tk0miya** [comment]
Thanks!

**Comment by KieranP** [comment]
Just spent hours trying to dig into why Hash#[] was always expecting return value, resulting in a bunch of "unreachable branch" warnings before finding this post. Looks like a new release is needed ASAP, because the latest release of steep allows the newest version of RBS, which no longer uses `Elem?` as return type, and has broken a lot of types.
