### ISSUE TITLE
@dynamic doesn't work on delegators

### ISSUE THREAD

**Issue by aaronmallen** [soutaro/steep#1394]
The `@dynamic` tag doesn't work on `forwardable` delegators:

```ruby
require 'forwardable'

class A
  def attr_accessor :foo
end

class B
  extend Forwardable
  
  # @dynamic foo
  def_delegators :@a, :foo

  def initialize
    @a = A.new
  end

  def set(new_value)
    foo = new_value
  end
end
```

```
[error] Type `::B` does not have method `foo`
│ Diagnostic ID: Ruby::NoMethod
│
└           foo = new_value
            ~~~~
```

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modify the AnnotationParser class to recognize and process @dynamic annotations for delegated methods, including those created by Forwardable. This change allows the type checker to correctly handle dynamically defined methods.

You can review changes in this commit: https://github.com/mnmnk43434/soutaro-steep-1394/commit/6f6e5ab8457aec4f31077f3b0589e9e0f93366b5.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
