### ISSUE TITLE
`steep check` fails with no messages

### ISSUE THREAD

**Issue by tadd** [soutaro/steep#158]
## Versions

- Steep 0.17.1
- RBS 0.4.0

## Concrete example

https://github.com/tadd/exp-steep-net-http (including `--verbose` log files)

## Details

I wrote a signature `net-http.rbs`:

```ruby
class Net::HTTP
  def self.start: (String, Integer) { (instance) -> void } -> void
end
```
And an implementation `app.rb`:

```ruby
require 'net/http'

class App
  def m
    # invalid call
    Net::HTTP.start
  end
end
```

Then, I executed a command `bundle exec steep check app.rb` but `steep` command failed without any outputs.

```
$ bundle exec steep check app.rb
$ echo $?
1
```

It runs well if I commented out the `Net::HTTP.start` line.

```
$ bundle exec steep check app.rb
$ echo $?
0
```

I tried the `--verbose` option in each run. The output message slightly differed.

```diff
-[Steep 0.17.1] [target=root] [target#type_check(target_sources: [app.rb], validate_signatures: true)] type checking 1 files took 0.023457556 seconds
-[Steep 0.17.1] [target=root] [target#type_check(target_sources: [app.rb], validate_signatures: true)] load signature and type check took 6.499966611 seconds
-[Steep 0.17.1] No type error found
+[Steep 0.17.1] [target=root] [target#type_check(target_sources: [app.rb], validate_signatures: true)] [synthesize:(1:1)] [synthesize:(3:1)] [synthesize:(4:3)] [synthesize:(6:5)] send
+[Steep 0.17.1] [target=root] [target#type_check(target_sources: [app.rb], validate_signatures: true)] [synthesize:(1:1)] [synthesize:(3:1)] [synthesize:(4:3)] [synthesize:(6:5)] [synthesize:(6:5)] const
+[Steep 0.17.1] [target=root] [target#type_check(target_sources: [app.rb], validate_signatures: true)] type checking 1 files took 0.010424531 seconds
+[Steep 0.17.1] [target=root] [target#type_check(target_sources: [app.rb], validate_signatures: true)] load signature and type check took 6.561480807 seconds
```

I doubt this is an internal bug of Steep.

**Comment by jeromegn** [comment]
I have the same issue in a small/medium rails app.

**Versions:**
- rbs (0.7.0)
- steep (0.21.0)
- rbs_rails (master)

**What I did:**
- I used `rbs_rails` to get Rails typings. Things still work fine when I do that
- I generated typings for all our models. This is when things got weird.

If I generate my types and they're in `sig/app/models/model_name.rbs`, it works fine. If I put them in `sig/gen/app/models/...` or `sig/app/models/gen/...`, it starts exhibiting the behavior mentioned in this issue.

I get similar logs with --verbose

```
$ bundle exec steep check --verbose
...
[Steep 0.21.0] [target=app] [target#type_check(target_sources: [app/models/organization.rb, app/models/application_record.rb], validate_signatures: true)] Validating class definition `::ActionController::Base`...
[Steep 0.21.0] [target=app] [target#type_check(target_sources: [app/models/organization.rb, app/models/application_record.rb], validate_signatures: true)] [::ActionController::Base] sig/rbs_rails/sig/generated/actionpack.rbs:907:32...907:39: Validating untyped...
[Steep 0.21.0] [target=app] [target#type_check(target_sources: [app/models/organization.rb, app/models/application_record.rb], validate_signatures: true)] load signature and type check took 6.528883814 seconds

$ echo $?
1
```

Our app is too big to try and create a minimal reproduction.

**Comment by tadd** [comment]
Unfortunately, this issue seems to be occurred again. I updated my example repository to use Steep master.
https://github.com/tadd/exp-steep-net-http
https://github.com/tadd/exp-steep-net-http/blob/5b276fd/Gemfile.lock#L2-L3

**Comment by tadd** [comment]
I might be wrong... It may be another problem. I'll try to investigate.
