### ISSUE TITLE
Guard clauses

### ISSUE THREAD

**Issue by timhatch** [soutaro/steep#162]
Steep **sometimes** fails to parse data filtered by a  guard clause.

Suppose method signatures as follow:
```ruby
def fetch: () -> (Hash[Symbol, untyped] | nil)
def parse: (String data) -> Hash[Symbol, untyped]
```

The following implementation of the relevant methods passes with no type-check errors:
```ruby
def fetch
  response = response_body_is_json_string_or_nil
  response ? parse(response) : nil
end

def parse(data)
  JSON.parse(data, symbolize_names: true).then { ... }
end
```

The following implementation of the relevant methods fails checking with error: `ArgumentTypeMismatch: receiver=self, expected=::String, actual=(::String | nil) (data)`:
```ruby
def fetch
  response = response_body_is_json_string_or_nil
  parse(response) unless response.nil?
end

def parse(data)
  JSON.parse(data, symbolize_names: true).then { ... }
end
```

Curiously, unwrapping the parse method to separate the JSON parsing and subsequent manipulation doesn't have the same problem, e.g. the following refactoring throws no errors during checking:
```ruby
def fetch: () -> (Hash[Symbol, untyped] | nil)
def parse: (Hash[Symbol, untyped] data) -> Hash[Symbol, untyped]
```
with implementation:
```ruby
def fetch
  response = response_body_is_json_string_or_nil
  JSON.parse(response, symbolize_names: true).then { |x| parse(x) } unless response.nil? 
end

def parse(data)
  do_stuff_with_data
end
```

So the problem is not guard structures per se, but I can't see what the problem is

**Comment by soutaro** [comment]
Hi @timhatch,

A workaround I can propose is using `if x` instead of `unless x.nil?`. This is because Steep currently doesn't know anything about `nil?` method call while it tries to reason local variable values based on the control flow.

If Steep knows the method returns true when the receiver `nil` and returns false otherwise, it can take care of branchings with `nil?`. However, I know this is sometimes annoying. Thinking of implementing a quick hack to support this...

**Comment by timhatch** [comment]
Hi @soutaro 

Thanks `parse(response) if response` is a work-around as `response` is truthy and that's good enough in this specific case, but I guess this won't work if the condition required some computation?

**Comment by soutaro** [comment]
> I guess this won't work if the condition required some computation?

Yes, and it is the problem. Steep currently implements the analysis conservatively so that it only unwrap optional types if it is a local variable. `nil?` may be overwritten, a method call may return different value next time, instance variables may be changed by other threads, etc...
