### ISSUE TITLE
A way to disable checking for certain line

### ISSUE THREAD

**Issue by take** [soutaro/steep#174]
Hi thanks for the awesome library!

Is there a way to skip `steep check` for certain line? 🤔 
I have the following code in my current project.

```ruby
class Foo
  def bar
    some_time = Time.current
    
    ...
  end
end
```

```
class Foo
  def bar: -> void
end
```

and `steep check` raises the following error

`NoMethodError: type=singleton(::Time), method=current (Time.current)`

I think this is because [`Time`'s type is defined in rbs](https://github.com/ruby/rbs/blob/64069601fc184624a55d10ede87936d716828a7d/stdlib/builtin/time.rbs), and Rails is extending that class without defining the method 🤔 

Is it possible to skip this line? :eyes: 

maybe #70 is related

**Comment by ybiquitous** [comment]
I think this feature is something like [`// @ts-expect-error` comments of TypeScript](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-9.html#-ts-expect-error-comments).

**Comment by ybiquitous** [comment]
As a workaround, the following code may help you:

```rbs
class Time
  def self.current: () -> untyped
end
```

**Comment by take** [comment]
> As a workaround, the following code may help you:
> class Time
>   def self.current: () -> untyped
> end

thanks! 🙏
