### ISSUE TITLE
Incompatible Assignment for Tuple of ancestors and Array with child types

### ISSUE THREAD

**Issue by johansenja** [soutaro/steep#192]
Imagine I have the following example, this works great:
```
# @type var a: [Integer, Float]
a = [0, 1.0]
```

I could also do something like this, and it works:
```
# @type var a: Numeric
# @type var b: Numeric
a, b = 0, 1.0
```

I would like to be able to adapt the first example to be a bit more flexible, like this:
```
# @type var a: [Numeric, Numeric]
a = [0, 1.0]
```
But this does not work 😕 Unless this behaviour is intentional?
```
test.rb:2:0: IncompatibleAssignment: lhs_type=[::Numeric, ::Numeric], rhs_type=::Array[(::Float | ::Integer)] (a = [0, 1.0])
  ::Array[(::Float | ::Integer)] <: [::Numeric, ::Numeric]
==> ::Array[(::Float | ::Integer)] <: [::Numeric, ::Numeric] does not hold
```

steep: 0.25.0
rbs: 0.10.0
ruby: 2.7.1

I upgraded from 0.24.0 to 0.25.0 when I saw #181 but unfortunately the behaviour was still the same

**Comment by soutaro** [comment]
Thank you for reporting the issue!

It's not intentional. It's a bug and will be fixed soon. 🙇‍♂️

**Comment by johansenja** [comment]
Sounds great thanks!
