### ISSUE TITLE
`steep check` raise ArgumentTypeMismatch for proc type

### ISSUE THREAD

**Issue by TomeHirata** [soutaro/steep#270]
### overview
When input type and output type of proc is defined in rbs file, steep raises ArgumentTypeMismatch error. It seems that steep cannot check input and output of the proc.

### example
```
#app.rb
class App
  def baz(fn)
    fn.call(5)
  end
end

proc1 = Proc.new { |n| n.to_s }

app = App.new
p app.baz(proc1)
```

```
#app.rbs
class App
  def baz: ( ^(Integer) -> (String)) -> untyped
end
```

$steep check
-> lib/app.rb:10:10: ArgumentTypeMismatch: receiver=::App, expected=^(::Integer) -> ::String, actual=::Proc (proc1)

**Comment by soutaro** [comment]
Continue with #335
