### ISSUE TITLE
Support: `Thread.new {}` raises UnexpectedBlockGiven

### ISSUE THREAD

**Issue by rramsden** [soutaro/steep#299]
Hey @soutaro, thanks for your hard work on this🙏 

Wasn't sure where to ask for support so posting a question here. I'm trying to use steep to type check one of my ruby libraries
but running into an issue with `Thread.new {}`.

Seems signature maybe incorrect (or more likely I am misunderstanding how RBS works). I have the following code:

```ruby
Thread.new do
  ...
end
```
and steep raises:

```ruby
Detected 1 problems from 1 files

lib/prb/timer_control.rb:11:17: [error] The method cannot be called with a block
│ Diagnostic ID: Ruby::UnexpectedBlockGiven
│
└       Thread.new do
```

How do I go about resolving the issue?

Thank you

**Comment by ybiquitous** [comment]
Hi @rramsden,

It seems this is a problem of RBS, not Steep.

Perhaps, the following PR should fix this problem, so could you please check it with the latest RBS and Steep?
https://github.com/ruby/rbs/pull/618

**Comment by soutaro** [comment]
`Thread.new` is fixed in https://github.com/ruby/rbs/pull/618. And, `Thread.start` is not fixed yet...
