### ISSUE TITLE
BreakTypeMismatch on break without an argument

### ISSUE THREAD

**Issue by ybiquitous** [soutaro/steep#302]
Hello, thanks for the nice release **0.40.0**!

In this version 0.40.0, I found a weird behavior about the use of `break` without an argument.

Here is a simple Ruby script named `a.rb` including 2 patterns of `break`:

```ruby
array = [1, 2, 3]
p array.each { break }       # break without an argument
p array.each { break array } # break with an argument
```

When running this script, it works expectedly:

```console
$ ruby a.rb
nil
[1, 2, 3]
```

But Steep reports an error in this script:

```console
$ bundle exec steep check
# Type checking files:

F

Detected 1 problems from 1 files

a.rb:2:15: [error] Cannot break with a value of type `nil` because type `::Array[::Integer]` is assumed
│   nil <: ::Array[::Integer]
│
│ Diagnostic ID: Ruby::BreakTypeMismatch
│
└ p array.each { break }
                 ~~~~~
```

Is this behavior expected and can I fix the script to avoid the Steep error?

Environment:

- Ruby: `ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin19]`
- Steep: `0.40.0`

<details>
<summary>Steepfile</summary>

```ruby
target :lib do
  signature "*.rbs"
  check "*.rb"
end
```

</details>

**Comment by soutaro** [comment]
This is intended behavior.

Breaking from `Array#each` will make the result of the method call `nil`, which is incompatible with its original return type, `Array[Integer]`. You need an annotation in the block:

```rb
array.each do
  # @type break: nil
  break
end
```

**Comment by ybiquitous** [comment]
@soutaro Thank you so much for your detailed explanation! I can fix such an error! 😄 👍 

One more question. Should `@type break` be put at the first line within a loop?

```ruby
array = [1, 2, 3]

# NG - within `if` block
array.each do |e|
  if e.odd?
    # @type break: nil
    break
  end
end

# OK - at the first line within `each` block
array.each do |e|
  # @type break: nil
  if e.odd?
    break
  end
end
```

```console
$ bundle exec steep check
# Type checking files:

F

Detected 1 problems from 1 files

a.rb:7:4: [error] Cannot break with a value of type `nil` because type `::Array[::Integer]` is assumed
│   nil <: ::Array[::Integer]
│
│ Diagnostic ID: Ruby::BreakTypeMismatch
│
└     break
      ~~~~~
```

**Comment by soutaro** [comment]
Ah, it may be a bug... I'm not sure if we should allow `@type break` inside `if`. Do you want to write it inside `if`?

**Comment by ybiquitous** [comment]
No. I can follow the rule of `@type break` position. 👍 

I thought we could write `@type break` within `if` block because I associated it with `@type var` (it is often written within `if`). 😅 

Thank you so much again! Please close this issue if you don't mind anything.

**Comment by ybiquitous** [comment]
FYI: Here is a PR of my organization's PR to update Steep. It works well. 👍 
https://github.com/sider/runners/pull/2004

**Comment by tibbon** [comment]
Perhaps I'm misunderstanding how Ruby works here.

```
class Foo
  def call
    records = ['foo', 'bar', 'baz', 'bat']
    counter = nil

    records.each_with_index do |_, i|
      counter = i + 10
      break if i % 3
    end
    
    counter
end
```

This (incredibly artificial code) `break` just breaks the .each loop right, it doesn't do an early return from the method overall? Why do I get this break type error? `[error] Cannot jump from here
│ Diagnostic ID: Ruby::UnexpectedJump`

**Comment by tibbon** [comment]
No amount of moving around a `# @type break: nil` seems to help
