### ISSUE TITLE
Different generic parameters are specified across definitions of `::Array`

### ISSUE THREAD

**Issue by jubishop** [soutaro/steep#327]
I have some code that adds a method to array, then I run `rbs prototype rb` on the file containing this method, and it seems reasonable.  but when I run `steep check` I'm told:

```
sig/array.rbs:1:0: [error] Different generic parameters are specified across definitions of `::Array`
│ Diagnostic ID: RBS::GenericParameterMismatch
│
└ class Array
  ~~~~~~~~~~~
  ```
  
  how do I support specifying definitions for methods added to the core classes?  thanks in advance!

**Comment by sxh** [comment]
Warning - I am a novice to RBS!

The core definition for Array looks like this:

`class Array[unchecked out Elem] < Object`

(see https://github.com/ruby/rbs/blob/master/core/array.rbs)

so you need to include the generic parameters when you reopen the definition in your code.

**Comment by jubishop** [comment]
boom!  that worked, thanks @sxh .  And now I know to check the core refs.  I just started looking at this yesterday, so compared to me you're an expert :)
