### ISSUE TITLE
`steep check` raise UnresolvedOverloading for Array#to_h with block

### ISSUE THREAD

**Issue by ybiquitous** [soutaro/steep#328]
## Description

`steep check` raises an `UnresolvedOverloading` error for the code using `Array#to_h` with a block.

Note: I'm not sure which this problem is caused by RBS or Steep, so I'll re-post this issue to [ruby/rbs](https://github.com/ruby/rbs) if the cause is RBS.

Here is the [latest RBS of `Array#to_h`](https://github.com/ruby/rbs/blob/e629aa7d9f5d55bcbba6632e598835a6651bc32c/core/array.rbs#L1855-L1856):

```ruby
class Array
  def to_h: () -> Hash[untyped, untyped]
          | [T, S] () { (Elem) -> [T, S] } -> Hash[T, S]
end
```

## Reproduction

<details open>
<summary>a.rb</summary>

```ruby
["abc", "d", ""].to_h { |e| [e, e.size] }
#=> {"abc"=>3, "d"=>1, ""=>0}
```

</details>

<details open>
<summary>Steepfile</summary>

```ruby
target :lib do
  check "*.rb"
end
```

</details>

<details open>
<summary>$ bundle exec steep check a.rb</summary>

```
# Type checking files:

F

a.rb:1:0: [error] Cannot find compatible overloading of method `to_h` of type `::Array[::String]`
│ Method types:
│   def to_h: () -> ::Hash[untyped, untyped]
│           | [T, S] () { (::String) -> [T, S] } -> ::Hash[T, S]
│
│ Diagnostic ID: Ruby::UnresolvedOverloading
│
└ ["abc", "d", ""].to_h { |e| [e, e.size] }
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Detected 1 problem from 1 file
```

</details>

## Environment

- Ruby: `ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin19]`
- Steep: `0.42.0`
- RBS: `rbs 1.1.0`

**Comment by soutaro** [comment]
Thank you for reporting this. This should be a bug. You can workaround if you add a type annotation in the block:

```
["abc", "d", ""].to_h { |e|
  # @type block: [String, Integer]
  [e, e.size]
}

```

**Comment by ybiquitous** [comment]
@soutaro Thanks for your feedback! The workaround works on my code. 👍
