### ISSUE TITLE
Cannot find compatible overloading of method `*` of type `::Integer`

### ISSUE THREAD

**Issue by jubishop** [soutaro/steep#331]
I receive the error:

```
Cannot find compatible overloading of method `*` of type `::Integer`
│ Method types:
│   def *: (::Float) -> ::Float
│        | (::Rational) -> ::Rational
│        | (::Complex) -> ::Complex
│        | (::Integer) -> ::Integer
```

Even tho the item being multiplied is of type `Float | Rational | Integer`.  If I change the type to just `Float`, just `Rational` or just `Integer` it works fine, but any Union of them causes this error.

**Comment by soutaro** [comment]
Confirmed but it cannot be fixed meanwhile. Filed a new ticket as #333. Thanks for your report!
