### ISSUE TITLE
Diagnostics error level configuration

### ISSUE THREAD

**Issue by soutaro** [soutaro/steep#362]
All diagnostics are reported in one of two levels, `error` and ignored. I plan to add more levels and let users configure theirselves.

## Configuration DSL

Giving a table from diagnostics classes to levels would be sufficient.

```ruby
D = Steep::Diagnostics

code_config = D.default.merge({ D::Ruby::NoMethod => :error, D::Ruby::UnexpectedBlockGiven => :warning })

target :lib do
  code_diagnostics code_config
end
```

* Users can find all possible keys under `Steep::Diagnostics::Ruby` module. 👍 
* Renaming class names would confuse the users. 👎 
  * Autoloading can help adding warning messages and providing a compatibility mode.

## Default configurations

I want to provide three default configurations of `default`, `lenient`, and `strict`.

**Comment by palkan** [comment]
That would be really great 👍 I wish we had an ability to silence some errors (e.g., `Ruby::UnsupportedSyntax` instead of ignoring the whole file).
