### ISSUE TITLE
Can't Interrogate Error

### ISSUE THREAD

**Issue by reedjosh1** [soutaro/steep#374]
Hello, thank you for your work. I've just started investigating, and I've not been able to get stats to work.

I'm getting error for all of my files when reviewing stats.

``` shell
 Target  File                     Status  Typed calls  Untyped calls  All calls  Typed %
---------------------------------------------------------------------------------------------------
 lib     lib/my_lib_file_here.rb  error             0              0          0      N/A
```

I tried setting the log level to info and reviewing, but the only `error` term I can find in the log is regarding ruby standard error classes.

Please point me to how to investigate the `error` status I'm seeing.

Side note: I did run typeprof and generate a steepfile first.

``` ruby
target :lib do
  signature "sig"

  check "lib"                       # Directory name
  check "Gemfile"                   # File name
end
```

**Comment by soutaro** [comment]
Hi @reedjosh1!

The `error` status means there is something and Steep cannot continue type checking, and there are three cases possible:

1. Ruby code has syntax error (with respect to 2.7 parser)
2. Type annotation has syntax error
3. Encoding error (UTF-8 is assumed)

How is the output of `steep check lib/my_lib_file_here.rb`?

**Comment by reedjosh1** [comment]
I see, that should have been obvious to me in retrospect. 

I have a ton of missing types--I believe because I put them all in files corresponding to lib files, but haven't done any work to combine them. That and I am just using `typeprof` generated `*rbs` files.

It may also be that we have C extensions in our lib that are missing in the `*.rbs` files too? IDK.

I'll close this now, and follow up once I figure out what was wrong with my setup for anyone else that lands here.
