### ISSUE TITLE
remove nil expectations based on static analysis for Array methods (ex: min)

### ISSUE THREAD

**Issue by HoneyryderChuck** [soutaro/steep#407]
Steep currently can't figure out whether arrays are empty or not, which leads to something like this:

```ruby
limit = [1, 2].min
# Cannot pass a value of type `(::Integer | nil)` as an argument of type `::Numeric`
#  (::Integer | nil) <: ::Numeric
#    nil <: ::Numeric(Ruby::ArgumentTypeMismatch)
#
# this goes if I add: return unless limit ; but then the code gets littered with such checks
return if 1 >= limit
```

**Comment by HoneyryderChuck** [comment]
Something similar happens in string, for certain methods, i.e. `"bla"[0,-1]` returns a string for sure.

**Comment by soutaro** [comment]
I'm sorry that I don't have plan for this. It needs much more powerful type language and I don't think we cannot start working for it now.

Adding an assertion in the code would be the best workaround for now, while it looks weird.

**Comment by HoneyryderChuck** [comment]
Understand that this isn't doable right now. But should this be closed?
