### ISSUE TITLE
`steep check` fails on `Enumerable#filter_map`

### ISSUE THREAD

**Issue by ybiquitous** [soutaro/steep#416]
Hi. I found a strange behavior when using the `steep check` command for the `Enumerable#filter_map` method.

I expect no errors, but an error occurs actually. Let me show the details:

### Reproduction

`Steepfile`:

```ruby
target :lib do
  signature "*.rbs"
  check "*.rb"
end
```

`a.rb`:

```ruby
class A
  def foo
    Dir.glob('*').filter_map { |path| path unless File.directory?(path) }
  end

  def bar
    Dir.glob('*')
  end
end

p A.new.foo, A.new.bar
```

`a.rbs`:

```ruby
class A
  def foo: () -> Array[String]
  def bar: () -> Array[String]
end
```

Run `steep check`:

```console
$ bundle exec steep check
# Type checking files:

............................................................F

a.rb:2:6: [error] Cannot allow method body have type `::Array[(nil | ::String)]` because declared as type `::Array[::String]`
│   ::Array[(nil | ::String)] <: ::Array[::String]
│     (nil | ::String) <: ::String
│       nil <: ::String
│
│ Diagnostic ID: Ruby::MethodBodyTypeMismatch
│
└   def foo
        ~~~

Detected 1 problem from 1 file
```

Run `a.rb` as a script:

```console
$ bundle exec ruby a.rb
["Gemfile", "Gemfile.lock", "Steepfile", "a.rb", "a.rbs"]
["Gemfile", "Gemfile.lock", "Steepfile", "a.rb", "a.rbs", "vendor"]
```

FYI. Here is the RBS definition of `Enumerable#filter_map`:
https://github.com/ruby/rbs/blob/v1.5.1/core/enumerable.rbs#L399-L400

### Environment

- ruby: `ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-darwin20]`
- bundler: `Bundler version 2.3.0.dev`
- rbs: `rbs 1.5.1`
- steep: `0.45.0`

---

If I'm wrong, please feel free to close it.
Thank you for reading. 😃

**Comment by soutaro** [comment]
Improved in https://github.com/soutaro/steep/pull/531.
