### ISSUE TITLE
Empty return does not trigger non-nullable type check

### ISSUE THREAD

**Issue by cromega** [soutaro/steep#467]
if I have to following rbs definition and code:

```
class Foo
  def bar: -> String
end
```

```ruby
class Foo
  def bar
    return
    "quux"
  end
end
```

Then running `steep check` does not cause an error.

if I change `return` to `return nil` then the type mismatch is reported.

Steepfile:

```
target :lib do
  signature "sig"
  check "lib"
end
```

**Comment by soutaro** [comment]
This is fixed by https://github.com/soutaro/steep/pull/500.
