### ISSUE TITLE
Optional parameter with wrong type default value is not treated as error

### ISSUE THREAD

**Issue by jljse** [soutaro/steep#470]
sig/test.rbs
```
class X
  def foo: (?String) -> void
end
```

test.rb
```
class X
  def foo(x = 1)
    p x
  end
end

X.new.foo('x')
```

These code doesn't show error.
I think default value `1` is error, because `X#foo` is explicitly typed.

My version is:
ruby 3.0.2p107
steep 0.47.0

**Comment by soutaro** [comment]
The original behavior was intentional. The `x` has a type of `Integer | String` and use of the variable inside the method will report an error.

The PR changes it to a type error to make things more explicit.
