### ISSUE TITLE
steep can't resolve simple .map call on array of strings

### ISSUE THREAD

**Issue by HoneyryderChuck** [soutaro/steep#475]
```ruby
puts %w[a b c].map(&:downcase)
```

running `steep check` on it:

```
file.rb:1:5: [error] Cannot find compatible overloading of method `map` of type `::Array[::String]`
│ Method types:
│   def map: [U] () { (::String) -> U } -> ::Array[U]
│          | () -> ::Enumerator[::String, ::Array[untyped]]
│
│ Diagnostic ID: Ruby::UnresolvedOverloading
│
└ puts %w[a b c].map(&:downcase)

**Comment by ksss** [comment]
Are you installing from source code instead of from rubygems?
Maybe it's because rbs 1.8 or later is not supported by steep.
https://github.com/soutaro/steep/pull/460

**Comment by HoneyryderChuck** [comment]
I'm using the master branch for everything,  given that steep and rbs latest break in several different ways (see my other issue reports)

**Comment by soutaro** [comment]
It's finally fixed in https://github.com/soutaro/steep/pull/516. 🙇‍♂️
