### ISSUE TITLE
UnexpectedError: missing keyword: :args(Ruby::UnexpectedError)

### ISSUE THREAD

**Issue by HoneyryderChuck** [soutaro/steep#476]
for the following code:

```ruby

# where k is untyped
Array(k).any? {}
```

I get the error

```
(::NilClass x) -> [ ]
[T] (::Array[T] x) -> ::Array[T]
[T] (::Range[T] x) -> ::Array[T]
[T] (::_Each[T] x) -> ::Array[T]
[K, V] (::Hash[K, V] x) -> ::Array[[ K, V ]]
[T] (T x) -> ::Array[T]
UnexpectedError: missing keyword: :args(Ruby::UnexpectedError)
```

I'm assuming steep doesn't handle the generic param yet?

**Comment by soutaro** [comment]
Closing because it's not reproducible with the latest branch.

I found another problem that passing `untyped` results in `[]` because it matches the `(NilClass) -> []` overload. This is not what we want here... 😫
