### ISSUE TITLE
Diagnostic Ruby::SyntaxError occurrence disables other diagnostics

### ISSUE THREAD

**Issue by lunatic-jan** [soutaro/steep#510]
This happens at least when using Ruby 3.1

Lets say I have a rbs file
```ruby
class Service
  def initialize: (params: Hash) -> void
end
```

and a class which uses Ruby shorthand hash syntax
```ruby
class Service
  def initialize(paramss:)
    process_params(params:)
  end
end
```

running `bundle exec steep check` shows a syntax error:
```
app/services/service.rb: [error] SyntaxError: unexpected token tRPAREN
│ Diagnostic ID: Ruby::SyntaxError
│
└     process_params(params:)
```

Which isn't valid error for Ruby 3.1. 

It only shows `Ruby::SyntaxError`, but not `Ruby::MethodParameterMismatch` or `Ruby::MethodArityMismatch`, which should happen from `def initialize(paramss:)`.

When above syntax error is fixed, then proper params errors are shown from steep check, but this is not solution, since I want to use shorthand hash syntax.

So I tried to disable Ruby::SyntaxError in Steepfile
```ruby
configure_code_diagnostics(D::Ruby.lenient.merge(D::Ruby::SyntaxError => nil))
```

Now, syntax errors are not shown, but other steep checks are still not executed.

Any clues why `Ruby::SyntaxError` stops other checks?
How can I disable `Ruby::SyntaxError`?

**Comment by soutaro** [comment]
Hi @lunatic-jan 👋 

Thank you for reporting the problem. Steep doesn't support the Ruby 3.1 syntax yet. So, the `SyntaxError` means the Ruby code is not loaded to Steep at all, thus the tool cannot detect any error.
