### ISSUE TITLE
Steep not handling is_a? calls inside all

### ISSUE THREAD

**Issue by HoneyryderChuck** [soutaro/steep#521]
Given the following code and signature:

```ruby
# def parse: (Array[String | File] texts) -> Array[String]
def parse(texts)
  if texts.all? { |text| text.is_a?(String) }
    texts
  else
    texts.map(&:read)
end
```

Steep throws the following error:

```
Ruby::MethodBodyTypeMismatch
Cannot allow method body have type `(::Array[::String] | ::Array[::File])` because declared as type `::Array[::String]`
....
```
  
possible related to other issues with type "unwrapping" that I've reported previously.

**Comment by soutaro** [comment]
Currently I don't have a plan to support this. Implementing the support may be possible, but it will be too much complicated.

**Comment by HoneyryderChuck** [comment]
should this still be closed, given that it may be possible to solve in the future?
