### ISSUE TITLE
[bug] use of unsupported Enumerable#filter_map method in ruby >=2.6.0,<2.7.0

### ISSUE THREAD

**Issue by tlubz** [soutaro/steep#563]
## Bug

In a few instances, steep is using `Enumerable#filter_map`, which is not supported until ruby 2.7.0, while the gemspec lists ruby 2.6.0 as the minimum ruby version. It's used in at least the following four places, and maybe others:

https://github.com/soutaro/steep/blob/master/lib/steep/type_construction.rb#L2313
https://github.com/soutaro/steep/blob/master/lib/steep/subtyping/check.rb#L620
https://github.com/soutaro/steep/blob/master/lib/steep/services/completion_provider.rb#L29
https://github.com/soutaro/steep/blob/master/lib/steep/services/hover_provider/ruby.rb#L13

#### Possible remedies

* the minimum version could be bumped to 2.7.0
* a backport could be applied (see workaround)
* `filter_map` could be replaced with chained `map` and `select` invocations

#### Temporary workaround:

We have a functioning workaround for this on our 2.6.5 system:

Copy the packaged `bin/steep` to a new executable in your source tree, e.g. `bin/steep-with-backport`. Add the following monkey patch before the `Steep::CLI#run` call:

```ruby
unless Enumerable.method_defined? :filter_map
  module Enumerable
    def filter_map
      return to_enum(:filter_map) unless block_given?

      each_with_object([]) do |item, res|
        processed = yield(item)
        res << processed if processed
      end
    end
  end
end
```

Then when calling `steep`, pass `--steep-command bin/steep-with-backport` to ensure that all worker processes use the monkey patch.

**Comment by soutaro** [comment]
Hi @tlubz 👋 

What version of Steep are you using? I believe the problem was fixed in 1.0.0. https://github.com/soutaro/steep/pull/544
