### ISSUE TITLE
A value of a less derived type can be assigned to a variable of a more derived type

### ISSUE THREAD

**Issue by mame** [soutaro/steep#6]
`bundle exec exe/steep check -I t.rbi t.rb` does say nothing against the following code.  Is this intended?

t.rbi 
~~~~
class A
  def foo: -> any
end

class B
  def foo: -> any
  def bar: -> any
end
~~~~

t.rb
~~~~
class A
  # @implements A

  def foo()
  end
end

# @type var b: B
b = A.new
b.bar
~~~~

(I found this behavior during investigating covariance of tuple.  Is there a good example of covariance in steep sample code?)

**Comment by soutaro** [comment]
Probably, `A.new` has `any` type here?

**Comment by mame** [comment]
Ah, I forgot `# @type const A: A.class`.  Adding this annotation solved the issue.  Sorry for the noise.
