### ISSUE TITLE
Where's the type definitions for the standard library?

### ISSUE THREAD

**Issue by thomthom** [soutaro/steep#620]
I have a library that adds extends some methods to the core classes, `String` and `Array`. When I try to validate the RBS file I generate with `steep` I get an error:

```
sig/sketchup.rbs:5337:0: [error] Different generic parameters are specified across definitions of `::Array`
│ Diagnostic ID: RBS::GenericParameterMismatch
│
└ class Array
  ~~~~~~~~~~~
```

I was hoping that matching the definition in my generated RBS file to the definition of the standard `Array` would make this work, but I'm not sure exactly what that definition is. Where can I find the type definitions for the standard library?

**Comment by kachick** [comment]
As far as I know, https://github.com/ruby/rbs/blob/0f5fdaa2246606fb8dea5a18e1db19458d655300/core/array.rbs is the Array definition. And Array will take generic as https://github.com/soutaro/steep/issues/621

I don't know if Steep officially supports modifying built-in classes.
However it looks like this is working in my code.

https://github.com/kachick/sandbox-steep/blob/40c716f2d73dc9562222d423e343df19523d5f71/issue-620/sig/array_ext.rbs#L1-L3
https://github.com/kachick/sandbox-steep/blob/40c716f2d73dc9562222d423e343df19523d5f71/issue-620/lib/example.rb#L1
