### ISSUE TITLE
How to use Enumerable?

### ISSUE THREAD

**Issue by thomthom** [soutaro/steep#621]
Given an example class:

```rb
class Something

  include Enumerable

  # @yield magic
  # @yieldparam [Integer] magic
  # @return void
  def each
    yield 123
  end

end
```

Using `sord` I get the following RBS file:
```rb
class Something
  include Enumerable

  # _@return_ — void
  def each: () ?{ (Integer magic) -> void } -> untyped
end
```

When I then run `steep check` I get the following errors:
```
# Type checking files:

............................................F.................F....

src/enum.rb:1:0: [error] UnexpectedError: sig/example.rbs:1:0...6:3: ::Enumerable expects parameters [Elem], but given args []
│ Diagnostic ID: Ruby::UnexpectedError
│
└ class Something
  ~~~~~~~~~~~~~~~

sig/example.rbs:1:0: [error] Type `::Enumerable` is generic but used as a non generic type
│ Diagnostic ID: RBS::InvalidTypeApplication
│
└ class Something
  ~~~~~~~~~~~~~~~

Detected 2 problems from 2 files
```

I've not been able to find any insights to how `Enumerable` should be correctly defined.
Any suggestions?

**Comment by kachick** [comment]
```diff
-include Enumerable
+include Enumerable[::Integer]
```

Looks resolve the issue.

You can check the behavior with following code.

https://github.com/kachick/sandbox-steep-621/blob/61122933b1526d768025a5414f22afa7611ef765/lib/something.rb#L14
https://github.com/kachick/sandbox-steep-621/blob/61122933b1526d768025a5414f22afa7611ef765/sig/somethig.rbs#L2

**Comment by thomthom** [comment]
That works, thanks. But what about enumerable types where each return key and value? `Enumerable` doesn't appear to accept multiple params; `include Enumerable[::Integer, ::String]`. ?

**Comment by kachick** [comment]
How do you think https://github.com/kachick/sandbox-steep/commit/dfd6d8edf66785490d8a542b8d3812b58d13a2fe?

**Comment by thomthom** [comment]
Perfect! Thank you. 👍
