### ISSUE TITLE
`&.` in type inference?

### ISSUE THREAD

**Issue by stevegeek** [soutaro/steep#693]
I just wanted to clarify if this is something I was misunderstanding or is not supported in `steep`

Take the following example:
```ruby
x = ARGV[0]&.to_i

if x && x.even?
  x = x + 1
end

puts x
```

This type checks fine with `steep check`

If however I change to use the safe navigation operator
```ruby
x = ARGV[0]&.to_i

if x&.even?
  x = x + 1
end

puts x
```

then `steep` seems to no longer infer that in the block of the conditional `x` is not `nil`

```
lib/test.rb:4:8: [error] Type `(::Integer | nil)` does not have method `+`
│ Diagnostic ID: Ruby::NoMethod
│
└   x = x + 1
          ~
```

Is this expected? Many thanks for any clarification!

**Comment by soutaro** [comment]
Hi @stevegeek,

Thank you for reporting the issue. It's not supported yet. Will fix it in future.

**Comment by stevegeek** [comment]
Great thanks!

**Comment by soutaro** [comment]
Continue working at https://github.com/soutaro/steep/issues/783.
