### ISSUE TITLE
Rails Type Definitions

### ISSUE THREAD

**Issue by ybiquitous** [soutaro/steep#70]
Is Rails type definitions planed to add?

For example:

- [`ActiveRecord`](https://api.rubyonrails.org/classes/ActiveRecord.html)
- [`ActionController`](https://api.rubyonrails.org/classes/ActionController.html)
- and so on...

If these types will be pre-defined, I predict Steep's users will increase.
Because defining these types is very hard task. 😓 

I would be glad if we could discuss about this theme! 😄

**Comment by soutaro** [comment]
I would like to have that in another gem, maybe `steep-types-rails` or something like that.

**Comment by ybiquitous** [comment]
It sounds good to me. 👍 

Then, for such gems having `*.rbi` file(s), I think that a central repository such as TypeScript's [DefinitelyTyped/DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) is useful for Steep contributors.

In other words, there are 2 ways:

- Gems with own `*.rbi` file(s). For example, [strong_json](https://github.com/soutaro/strong_json) gem.
- Gems without own `*.rbi` file(s). These `*.rbi` file(s) are provided in the **central repository** above such as _DefinitelyTyped/DefinitelyTyped_.

What do you think about this idea?

**Comment by ybiquitous** [comment]
Now we have the repository [ruby/gem_rbs](https://github.com/ruby/gem_rbs) for 3rd-party type definitions.

So, I think this issue should be closed. (feel free to open if you need it still)
