### ISSUE TITLE
False positive warning for setter methods

### ISSUE THREAD

**Issue by hjwylde** [soutaro/steep#729]
It looks like Steep is warning about incorrect types for void contexts in setters. Setters in Ruby ignore any value passed to `return` and always return the argument passed.

```
# .rb
class Foo
  def foo=(arg)
    return if rand > 0.5 # Steep shows a warning here, but there should be no warning as `nil` isn't actually returned, `arg` is still returned
   @foo = arg
  end
end
```
```
# .rbs
class Foo
  def foo=: (String) -> String
end
```

**Comment by soutaro** [comment]
The setter syntax `obj.attr = x` always returns the right-hand-side value. The attribute setter method, `def attr=(value) ...` can have any implementation.

```rb
Foo.new.foo = 123         # Always 123
Foo.new.__send__(:foo=)   # Maybe nil
```

I'm assuming the method implementation should follow the method signature, and Steep type checks the setter syntax correctly.

**Comment by hjwylde** [comment]
> I'm assuming the method implementation should follow the method signature, and Steep type checks the setter syntax correctly.

Hmm, I came across this problem because I had a setter type signature `(T) -> T`, and RuboCop warned about an early `return xyz` in the setter (https://msp-greg.github.io/rubocop/RuboCop/Cop/Lint/ReturnInVoidContext.html), saying that it needed to just be `return` as the `xyz` is thrown out (as setter calls always return the right hand side value), but then Steep warns when there are no arguments passed to the `return` (as it's trying to type check the implementation).

From this I actually think that the method implementation doesn't need to follow the method signature, as any returned values are thrown out. This is the approach RuboCop takes at least, and it would be nice if Steep/RuboCop were aligned in their checks?

**Comment by soutaro** [comment]
Hmm, I'd add an option to skip type checking setter return type...

**Comment by hjwylde** [comment]
Thanks Soutaro!
