### ISSUE TITLE
Suspect type inference in singleton methods

### ISSUE THREAD

**Issue by noproblemwiththat** [soutaro/steep#747]
Many thanks for steep, fabulous tooling.  On setting up for a project of mine, I think I hit a bad type inference: minimal example
```ruby
# lib/a.rb
class A
  def self.foo
    new
  end
end

class B < A
  def self.foo
    super
  end
end

puts A.foo.inspect
puts B.foo.inspect
```
Output:
```
#<A:0x000055f7cfb03908>
#<B:0x000055f7cfb037f0>
```
Signature
```ruby
# lib/a.rbs
class A
  def self.foo: () -> A
end

class B < A
  def self.foo: () -> B
end
```
result of `steep check`
```
lib/a.rb:8:11: [error] Cannot allow method body have type `::A` because declared as type `::B`
│   ::A <: ::B
│     ::Object <: ::B
│       ::BasicObject <: ::B
│
│ Diagnostic ID: Ruby::MethodBodyTypeMismatch
│
└   def self.foo
             ~~~
```
I'm running steep 1.3.2 in the above.

**Comment by soutaro** [comment]
Hi @noproblemwiththat,

This is an expected behavior. The RBS type definition says `A.foo` returns `A`, and thus the `super` call returns `A` that is not `B`.

Using `instance` type may help you, which requires additional type annotations or casts in the `foo` methods implementations.

```rbs
class A
  def self.foo: () -> instance
end

class B < A
  def self.foo: () -> instance
end
```

**Comment by noproblemwiththat** [comment]
Quite right, `instance` fixes my issue, many thanks (and apologies for noise).
