### ISSUE TITLE
Signature help will be closed on inputting the 2nd keyword argument

### ISSUE THREAD

**Issue by tk0miya** [soutaro/steep#834]
Signature help will be closed unexpectedly on inputting the 2nd keyword argument.

In this case, the signature help window was closed on inputting the 2nd keyword argument `noop` for `FileUtils.cp`:
![preview](https://github.com/soutaro/steep/assets/748828/a5193263-0489-49f8-95c5-9e10ddb6b0d6)

Inside the InteractionWorker, inputting the 2nd argument will cause SyntaxError because `noop` is considered a positional argument after the keyword argument.
I got a `#<Parser::SyntaxError: unexpected token tRPAREN>` exception on parsing on I input the first character of `noop`.

And it will close the signature help window. It would be better to keep the window even if SyntaxError is raised.

Is sending the latest signature help response better if SyntaxError is raised?

**Comment by soutaro** [comment]
Completed.
