### ISSUE TITLE
`steep check` says it cannot find Ruby core type `SimpleDelegator`

### ISSUE THREAD

**Issue by radar** [soutaro/steep#862]
I've got a small Ruby project over here that I'm trying to typecheck: https://github.com/radar/mtg/tree/b84898b82f4ae0899cdf69daef9ddf5cc2961500

When I run:

```
steep check sig
```

I see:

```
sig/magic/permanent.rbs:39:4: [error] Cannot find type `SimpleDelegator`
│ Diagnostic ID: RBS::UnknownTypeName
│
└     class Protections < SimpleDelegator
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Are there missing types in RBS for SimpleDelegator? 

(Seems possibly related to #624)

**Comment by soutaro** [comment]
Moved to the rbs repo.
