### ISSUE TITLE
Option or configuration to exclude paths

### ISSUE THREAD

**Issue by vinistock** [soutaro/steep#93]
Hey! I am trying to adopt steep for a gem that includes generators. However, running `steep check` breaks on the generator's template files with the following error:

`#<Parser::SyntaxError: unterminated string meets end of file>`

Template files really don't need to be type checked, so I was wondering if there's a way to exclude certain paths from `steep check` either by a configuration file (say something like `.steep.yml` or by a command line argument).

I suspect the changes to exclude paths would have to be done somewhere in [here](https://github.com/soutaro/steep/blob/4bd719d6d92d41855a97dc77dfb77cfe0c6d4026/lib/steep/cli.rb#L146). Let me know your ideas and I can put a pull request together if you wish to implement this.

Thanks!

**Comment by vinistock** [comment]
I see. Do you mind if I try to put together an implementation for a simple configuration file? I'd love to help.

**Comment by soutaro** [comment]
@vinistock Sounds great.

I have written a document discussing the project file. My opinion is going though Ruby syntax, as in the *proposal* section. If you consider trying to implement, feedbacks are welcome!

https://hackmd.io/CrFK56eATgengAfZWyOI5Q

**Comment by vinistock** [comment]
I really like the idea of the `Steepfile`. I am working on a sample implementation to get your ideas on it.

However, I am facing two issues (which might be related). When I try to run individual tests or open the console, I get the error `Cannot find ruby/signatures`. And if I run `bundle exec rake test` I end up in an endless loop. Am I missing something?

**Comment by soutaro** [comment]
Ah, it is because `ruby-signature` is bundled as a git submodule now. Try `rake reset` to sync the submodule.
